name: Publish to GitHub Packages with pnpm
on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build
      - name: Publish to npm
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}